# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TestTest
      MYSQL_USER: piler
      MYSQL_PASSWORD: piler
      MYSQL_DATABASE: piler
    volumes:
      - /var/piler-mariadb:/var/lib/mysql

  piler:
    image: ebtc/piler
    restart: always
    ports:
      - "2525:25"
      - "8025:80"
    volumes:
      - /var/piler-data:/var/piler
      - /var/piler-config:/etc/piler
    environment:
      PILER_HOST: archive.domain.com
      MYSQL_HOSTNAME: db
      MYSQL_ROOT_PASSWORD: TestTest
      MYSQL_USER: piler
      MYSQL_PASSWORD: piler
