# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TestTest
      MYSQL_USER: piler
      MYSQL_PASSWORD: piler
      MYSQL_DATABASE: piler
    volumes:
      - /var/piler-test-mariadb:/var/lib/mysql

  service:
    image: pilertest:latest
    restart: always
    ports:
      - "2525:25"
      - "8025:80"
    volumes:
      - /var/piler-test-data:/var/piler
      - /var/piler-test-config:/etc/piler
    environment:
      PILER_HOST: localhost
      MYSQL_HOSTNAME: db
      MYSQL_ROOT_PASSWORD: TestTest
      MYSQL_USER: piler
      MYSQL_PASSWORD: piler
