name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      # org run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
        export VCS_REF_VAR=`git rev-parse — short HEAD`
        export BUILD_DATE_VAR=`date -u +”%Y-%m-%dT%H:%M:%SZ”`
        docker build --build-arg VCS_REF=$BUILD_DATE_VAR --build-arg BUILD_DATE=$BUILD_DATE_VAR --file Dockerfile --tag my-image-name:$(date +%s)
        printenv
